version: '3.1'
services:
  mysql-5.7:
    container_name: mysql5.7
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./config/:/etc/mysql/conf.d
